# 9.例外

在一个完美的世界里，程序员从不犯错，用户也总是表现良好。在现实世界中，程序员总是会犯错，用户也从来不会循规蹈矩！当出错时，Python 会抛出异常，这是程序执行时遇到的错误。幸运的是，处理大多数异常并从中恢复是可能的。在这一章中，我们将学习一些我们应该预料到的常见异常，以及如何处理它们。

## 验证用户输入

假设您想收集一些关于用户的基本数据，然后将一些信息返回给他们。这似乎很简单:

```py
1   name = input("Please enter your name: ")
2   age = input("Please enter your age: ")
3   print("You were born in {}.".format(2015 - int(age)))

```

你测试了程序，它运行得很好。然后你把它给你的朋友看，她输入“25 年”作为年龄。好吧，这个无用的信息转储到屏幕上，现在看起来你不知道如何编程。

```py
Traceback (most recent call last):
  File "validate.py", line 3, in <module>
    print("You were born in {}.".format(2015 - int(age)))
ValueError: invalid literal for int() with base 10: '25 years'

```

这是一个异常(特别是一个`ValueError`)，引发它是因为用户输入了一个不能用`int()`转换成数字的值。作为勤奋的程序员，我们可以预见和计划这种情况。

关键字`try`允许我们将代码块标记为可能引发异常的东西。接下来是`except`关键字，它标记了遇到异常时要运行的代码块。

```py
1   name = input("Please enter your name: ")
2   age = input("Please enter your age: ")
3   try:
4       print("You were born in {}.".format(2015 - int(age)))
5   except ValueError:
6       print('Unable to calculate the year you were born, ' \
7             + '"{}" is not a number.'.format(age))

```

特别注意这里的语法，记住 Python 中的空格是有意义的。缩进告诉我们什么代码是`try`块的一部分，什么代码是`except`块的一部分。如果`try`块中的任何代码遇到`ValueError`，程序将立即跳转到`except`块并运行该块中的代码。

## 检查对象成员

在我们的游戏中，玩家有一些不同的物品清单。我们再补充一个:

```py
inventory = [Rock(), Dagger(), 'Gold(5)', 'Crusty Bread']

```

有些是武器，有些不是。如果我们想在清单中找到最强大的武器，我们需要检查每个项目，看看它的损害是什么。

```py
59   def most_powerful_weapon(inventory):
60       max_damage = 0
61       best_weapon = None
62       for item in inventory:
63           if item.damage > max_damage:
64              best_weapon = item
65              max_damage = item.damage
66
67       return best_weapon

```

这应该很简单。该函数循环遍历库存中的所有商品，并检查损失是否大于已经发现的损失。这里新增了一个关键词:`None`。这是一种价值的缺失。我们最初设置`best_weapon`等于`None`,因为如果玩家没有任何武器，这个函数不能返回武器！

如果运行这段代码，很不幸会引发一个异常:

```py
Traceback (most recent call last):
  File "game.py", line 80, in <module>
    play()
  File "game.py", line 46, in play
    best_weapon = most_powerful_weapon(inventory)
  File "game.py", line 59, in most_powerful_weapon
    if item.damage > max_damage:
AttributeError: 'str' object has no attribute 'damage'

```

这是有道理的，因为“硬皮面包”和“黄金”不会造成损害。因为我们知道库存经常会有非武器，所以我们可以将代码包装在一个`try`中并处理`AttributeError`。

```py
59   def most_powerful_weapon(inventory):
60       max_damage = 0
61       best_weapon = None
62       for item in inventory:
63           try:
64               if item.damage > max_damage:
65                   best_weapon = item
66                   max_damage = item.damage
67           except AttributeError:
68               pass

69
70       return best_weapon
71
72   play()

```

如果遇到了一个`AttributeError`，我们实际上不需要做任何事情，因为我们并不在乎 Crusty Bread 没有一个`damage`属性。关键字`pass`可以在我们想跳过或忽略代码块的任何时候使用。请记住，对于大多数异常，您需要做一些事情，比如警告用户或遵循不同的代码路径。对于这种特定的情况，我们可以安全地忽略这个异常。

## 故意引发异常

乍一看，这似乎有悖常理，但在某些情况下，我们确实希望引发一个异常。当我们想对自己做错的事情大喊大叫时，我们通常会这样做！对坏代码进行检查将有助于我们在测试过程中发现错误。

当前代码中的一个漏洞与`Weapon`类有关。此代码将导致异常:

```py
1   axe = Weapon()
2   print(axe)

```

为什么呢？因为`Weapon`类的`__str__()`方法在打印对象时会寻找一个`name`，但是该类没有那个属性。我们可以通过给`Weapon`指定一个名字来解决这个问题，但是这实际上没有意义，因为这个类太普通了，无法描述。真的，我们永远不应该创造一个`Weapon`对象；我们应该始终创建一个类似`Dagger`的特定子类。如果我们需要一个 axe 对象，我们应该创建一个继承自超类`Weapon`的`Axe`类。

为了防止我们自己意外地创建了`Weapon`对象，我们可以在初始化器中引发一个异常。

```py
1   class Weapon:
2       def __init__(self):
3           raise NotImplementedError("Do not create raw Weapon objects.")
4
5       def __str__(self):
6           return self.name

```

Python 内置了`NotImplementedError`异常，它是一个很好的标记，提醒我们正在做错事。我们可以为异常包含一条消息，以帮助提醒我们问题是什么。如果你想测试这个新代码，试着将`Weapon()`添加到玩家的物品清单中并运行游戏。您应该会看到以下错误:

```py
Traceback (most recent call last):
  File "game.py", line 72, in <module>
    play()
  File "game.py", line 33, in play
    inventory = [Weapon(), Rock(), Dagger(), 'Gold(5)', 'Crusty Bread']
  File "game.py", line 3, in __init__
    raise NotImplementedError("Do not create raw Weapon objects.")
NotImplementedError: Do not create raw Weapon objects.

```

当你完成测试时，记得从清单中删除`Weapon()`。

## 家庭作业

尝试以下作业:

1.  用`try`和`except`更新`user_calculator.py`来处理没有输入数字的用户。
2.  `None`是什么意思，什么时候用？
3.  `pass`是什么意思，什么时候用？
4.  创建一个`Vehicle`类，一个`Motorcycle`类是`Vehicle`的子类，其`wheels`属性设置为 2，一个`Car`类是`Vehicle`的子类，其`wheels`属性设置为 4。添加代码，如果程序员试图创建一个`Vehicle`，将引发一个异常。